### ISSUE TITLE
Deployed app contains `*.map` files

### ISSUE THREAD

**Issue by chalin** [dart-lang/angular_components_example#80]
The deployed app (from [gh-pages](https://github.com/dart-lang/angular_components_example/tree/gh-pages)) contains `*.map` files. Is that intentional? If not, they should be stripped out / not generated.

cc @kwalrath @kevmoo

**Comment by nshahan** [comment]
Yeah, I can add `--no-source-maps` to the release options for dart2js.

**Comment by kevmoo** [comment]
Is there a scenario where we want to debug things?

I guess we can always rebuild the exact thing locally – so maybe good to get rid of.

**Comment by TedSander** [comment]
I have a counter to that. Internally we actually release all the .map files, and host all the dart files when we release. We do this so that developers can debug the gallery if they want and see how things are working.

The primary goal is for this to help developers. It should have the best practices we know about, but I don't really want to put a lot of work to make it as `slim n trim` as possible as that is not the purpose of it. The purpose is to document/help/showcase the widgets to developers.

**Comment by kevmoo** [comment]
As Ted said (upon reflection) it doesn't cost anything to ship the .map
files – unless someone has the console open.

**Comment by chalin** [comment]
Sure, that works for me, the problem is that the *.dart files aren't [being published](https://github.com/dart-lang/angular_components_example/tree/gh-pages). Shouldn't they?

**Comment by nshahan** [comment]
@kevmoo What would be the easiest way to let the .dart files be included when I build the gh-pages branch with peanut?

**Comment by kevmoo** [comment]
You need to tweak the `build.yaml` file – @natebosch understands the bits here, I think

**Comment by natebosch** [comment]
You're explicitly configuring outputs from `dart2js` to [not get filtered](https://github.com/dart-lang/angular_components_example/blob/63214f8f6036d091f1c807aee4de446f0281011d/example/angular_components_example/build.yaml#L17). What are the outputs that you want to keep from `dart2js` that are _not_ `.js` or `.js.map`? Do we need to make the configuration more expressive to let you keep some other file while dropping the sourcemap files?

If you want instead to also keep `.dart` files you can add

```yaml
      dart_web_compilers|dart_source_cleanup:
        options:
          enabled: false
```

**Comment by natebosch** [comment]
Looks like you wanted to [keep the dumpinfo](https://github.com/dart-lang/angular_components_example/pull/85) - why do you want that in release builds? If you feel it's important you can file an issue on the build repo asking for configuration which allows you to retain dumpinfo while removing sourcemaps. We'd have to introduce a new configuration option.

**Comment by kevmoo** [comment]
I'd like it just so it's trivial to track dart2js output stats across
releases...

**Comment by nshahan** [comment]
> Looks like you wanted to keep the dumpinfo - why do you want that in release builds? If you feel it's important you can file an issue on the build repo asking for configuration which allows you to retain dumpinfo while removing sourcemaps.

@natebosch We do want serve the source maps and original dart files too. For the gallery it is helpful even from the published release to make experimenting with the live examples easier. Probably not something that most projects would want to do though.

**Comment by natebosch** [comment]
> We do want serve the source maps and original dart files too.

SG, looks like you want

```yaml
      dart_web_compilers|dart_source_cleanup:
        options:
          enabled: false
```

**Comment by nshahan** [comment]
@natebosch I'm having some issues getting it working. I tried a slightly modified version of the options you posted:

```yaml
build_web_compilers|dart2js_archive_extractor:
    release_options:
        filter_outputs: false
build_web_compilers|dart_source_cleanup:
    release_options:
        enabled: false
```
I'm not sure the build is invalidated when changing these options (that might need an issue filed) but after running `pub run build_runner clean` and then running my release build again I still don't have the  .dart sources available.

**Comment by natebosch** [comment]
@nshahan do you have a PR open so I can try to repro?

**Comment by natebosch** [comment]
oh, I just realized that the dart_source_cleanup needs to be disabled globally.

```yaml
global_options:
  build_web_compilers|dart_source_cleanup:
    options:
      enabled: false
```
